name: MC-Generations
version: ${project.version}
main: io.georgeous.mcgenerations.MCG
api-version: 1.18
commands:
  dayspeed:
  gm:
  you:
  die:
  me:
  pets:
  secinyear:
  debug:
  nick:
  family:
  role:
  msg:
  w:
  say:
  howto:
  discord:
  broadcast:
  babyhandler:
  report:
  rules:
  adopt:
  shareign:
depend: [Piggyback, NickAPI, Petmanager, Spicyhearts]

