name: MC-Generations
version: ${project.version}
main: io.georgeous.mcgenerations.Main
api-version: 1.17
commands:
  age:
    description: Set age of player
  you:
  me:
  pets:
  renamefamily:
  secinyear:
  debug:
  nick:
depend: [Piggyback, NickAPI]

