name: MC-Generations
version: ${project.version}
main: io.georgeous.mcgenerations.MCG
api-version: 1.17
commands:
  dayspeed:
  gm:
  you:
  die:
  me:
  pets:
  secinyear:
  debug:
  nick:
  family:
  role:
  msg:
  w:
  say:
depend: [Piggyback, NickAPI, Petmanager]

